# Generated by Django 5.2.12 on 2026-03-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboards", "0002_dashboardsharelink"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dashboardwidget",
            name="widget_type",
            field=models.CharField(
                choices=[
                    ("kpi", "KPI"),
                    ("bar", "Bar"),
                    ("line", "Line"),
                    ("pie", "Pie"),
                    ("doughnut", "Doughnut"),
                    ("area", "Area"),
                    ("hbar", "Horiz. Bar"),
                    ("scatter", "Scatter"),
                    ("radar", "Radar"),
                    ("table", "Table"),
                ],
                max_length=16,
            ),
        ),
    ]
