# Generated by Django 5.2.12 on 2026-03-22 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboards", "0004_dashboardwidget_source_dataset_version_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dashboardwidget",
            name="widget_type",
            field=models.CharField(
                choices=[
                    ("kpi", "KPI"),
                    ("bar", "Bar"),
                    ("line", "Line"),
                    ("pie", "Pie"),
                    ("doughnut", "Doughnut"),
                    ("area", "Area"),
                    ("hbar", "Horiz. Bar"),
                    ("scatter", "Scatter"),
                    ("radar", "Radar"),
                    ("table", "Table"),
                    ("heading", "Heading"),
                    ("text_canvas", "Text Canvas"),
                    ("bubble", "Bubble"),
                    ("polararea", "Polar Area"),
                    ("mixed", "Mixed"),
                    ("funnel", "Funnel"),
                    ("gauge", "Gauge"),
                    ("waterfall", "Waterfall"),
                ],
                max_length=16,
            ),
        ),
    ]
