# Generated by Django 5.2.12 on 2026-03-22 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboards", "0005_add_pro_widget_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="dashboard",
            name="filter_config",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
