# Generated by Django 5.2.12 on 2026-03-22 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0006_add_dashboard_filter_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardwidget',
            name='widget_type',
            field=models.CharField(choices=[('kpi', 'KPI'), ('bar', 'Bar'), ('line', 'Line'), ('pie', 'Pie'), ('doughnut', 'Doughnut'), ('area', 'Area'), ('hbar', 'Horiz. Bar'), ('scatter', 'Scatter'), ('radar', 'Radar'), ('table', 'Table'), ('heading', 'Heading'), ('text_canvas', 'Text Canvas'), ('bubble', 'Bubble'), ('polararea', 'Polar Area'), ('mixed', 'Mixed'), ('funnel', 'Funnel'), ('gauge', 'Gauge'), ('waterfall', 'Waterfall'), ('map', 'Map')], max_length=16),
        ),
    ]
