# Generated by Django 5.2.12 on 2026-03-22 12:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboards", "0006_add_dashboard_filter_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="dashboard",
            name="build_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("building", "Building"),
                    ("ready", "Ready"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="dashboard",
            name="celery_task_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="dashboard",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="dashboardwidget",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="dashboardwidget",
            name="widget_type",
            field=models.CharField(
                choices=[
                    ("kpi", "KPI"),
                    ("bar", "Bar"),
                    ("line", "Line"),
                    ("pie", "Pie"),
                    ("doughnut", "Doughnut"),
                    ("area", "Area"),
                    ("hbar", "Horiz. Bar"),
                    ("scatter", "Scatter"),
                    ("radar", "Radar"),
                    ("table", "Table"),
                    ("heading", "Heading"),
                    ("text_canvas", "Text Canvas"),
                    ("divider", "Divider"),
                    ("bubble", "Bubble"),
                    ("polararea", "Polar Area"),
                    ("mixed", "Mixed"),
                    ("funnel", "Funnel"),
                    ("gauge", "Gauge"),
                    ("waterfall", "Waterfall"),
                    ("map", "Map"),
                ],
                max_length=16,
            ),
        ),
    ]
