# Generated by Django 5.2.12 on 2026-03-22 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0007_alter_dashboardwidget_widget_type'),
        ('dashboards', '0007_uuid_primary_keys_and_build_status'),
    ]

    operations = [
    ]
